### ISSUE TITLE
error: ‘struct snd_id14_chip’ has no member

### ISSUE THREAD

**Issue by lbm-services** [charlesmulder/alsa-audient-id14#1]
Why should I remove a module before building a new one? 
Anyway on my machine the make command should look like this:
` KERNELDIR=/lib/modules/4.15.0-20-generic/build/ make`

which results in this error:

```
  CC [M]  /home/hli/Downloads/alsa-audient-id14/chip.o
/home/hli/Downloads/alsa-audient-id14/chip.c: In function ‘snd_id14_chip_abort’:
/home/hli/Downloads/alsa-audient-id14/chip.c:36:11: error: ‘struct snd_id14_chip’ has no member named ‘control’
   if (chip->control)
           ^~
/home/hli/Downloads/alsa-audient-id14/chip.c:37:4: error: implicit declaration of function ‘snd_id14_control_abort’; did you mean ‘snd_id14_chip_abort’? [-Werror=implicit-function-declaration]
    snd_id14_control_abort(chip);
    ^~~~~~~~~~~~~~~~~~~~~~
    snd_id14_chip_abort
/home/hli/Downloads/alsa-audient-id14/chip.c: In function ‘snd_id14_chip_destroy’:
/home/hli/Downloads/alsa-audient-id14/chip.c:49:11: error: ‘struct snd_id14_chip’ has no member named ‘control’
   if (chip->control)
           ^~
/home/hli/Downloads/alsa-audient-id14/chip.c:50:4: error: implicit declaration of function ‘snd_id14_control_destroy’; did you mean ‘snd_id14_chip_destroy’? [-Werror=implicit-function-declaration]
    snd_id14_control_destroy(chip);
    ^~~~~~~~~~~~~~~~~~~~~~~~
    snd_id14_chip_destroy
/home/hli/Downloads/alsa-audient-id14/chip.c: In function ‘usb_id14_audio_probe’:
/home/hli/Downloads/alsa-audient-id14/chip.c:124:8: error: implicit declaration of function ‘snd_id14_control_init’; did you mean ‘snd_card_info_init’? [-Werror=implicit-function-declaration]
  ret = snd_id14_control_init(chip);
        ^~~~~~~~~~~~~~~~~~~~~
        snd_card_info_init
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/home/hli/Downloads/alsa-audient-id14/chip.o' failed
make[2]: *** [/home/hli/Downloads/alsa-audient-id14/chip.o] Error 1
Makefile:1552: recipe for target '_module_/home/hli/Downloads/alsa-audient-id14' failed
make[1]: *** [_module_/home/hli/Downloads/alsa-audient-id14] Error 2
make[1]: Verzeichnis „/usr/src/linux-headers-4.15.0-20-generic“ wird verlassen
Makefile:16: recipe for target 'modules' failed
make: *** [modules] Error 2
```
Any help appreciated.
On Linuxmint 19 Audient id14 works out of the box, by the way, but I wanted to know if your module adds some benefits.

**Comment by charlesmulder** [comment]
Hi @lbm-services . 

Thanks for commenting. 

This module is still a work in progress. Apart from being a loadable kernel module that echoes a bunch of stuff, It doesn't do much at the moment. 

Over the course of 2018 I spent some of my free time reading the USB spec, USB audio spec, ALSA docs etc, to see how much work it would be to write a driver from scratch. It turns out, it's quite a time commitment for someone new to kernel development.

I was hoping to return to this when I have some free time, but if you say the ID14 works out of the box on Linux Mint, it might not be of much use.  

I hope to revisit this at some stage in the future. 

Thanks for commenting though. 

Are you perhaps able to help? Would be great to have someone to help me figure this out.

**Comment by charlesmulder** [comment]
@lbm-services 

RE your question:

> Why should I remove a module before building a new one?

On Ubuntu and Debian the snd-usb-audio module is automatically assigned to the device interfaces, which means the id14 module, can't access the interfaces, cause they've already been claimed by the snd-usb-audio module.

An easy and short term solution to this problem is unloading the snd-usb-audio module, before loading my id14 module. 

I'm not yet sure how to deal with this in the longer term, but I imagine it may entail adding the device to a module blacklist of some kind. Just a guess.

**Comment by lbm-services** [comment]
> I was hoping to return to this when I have some free time, but if you say the ID14 works out of the box on Linux Mint, it might not be of much use.

That is true for playback only. If you want to record with ID14 there are some settings only available via the Windows driver, which makes it useless for Linux users. Finally I bought a Focusrite 2i2 which works perfectly without Windows drivers.
